/*
 * port.cpp
 *
 *  Created on: Aug 24, 2019
 *      Author: David Fiumano
 */

#include "eUSCI_A.h"

namespace SatLib
{
    const eUSCI_A_Type eUSCI_A_Modules[] =
    {
     {&P2SEL0, &P2SEL1, 0, (BIT0 | BIT1), &UCA0TXBUF, &UCA0RXBUF, &UCA0MCTLW, &UCA0CTLW0, &UCA0BRW, &UCA0IE, &UCA0IFG, &UCA0IV},
     {&P2SEL0, &P2SEL1, 0, (BIT5 | BIT6), &UCA1TXBUF, &UCA1RXBUF, &UCA1MCTLW, &UCA1CTLW0, &UCA1BRW, &UCA1IE, &UCA1IFG, &UCA1IV},
     {&P5SEL0, &P5SEL1, (BIT5 | BIT6), 0, &UCA2TXBUF, &UCA2RXBUF, &UCA2MCTLW, &UCA2CTLW0, &UCA2BRW, &UCA2IE, &UCA2IFG, &UCA2IV},
     {&P6SEL0, &P6SEL1, (BIT0 | BIT1), 0, &UCA3TXBUF, &UCA3RXBUF, &UCA3MCTLW, &UCA3CTLW0, &UCA3BRW, &UCA3IE, &UCA3IFG, &UCA3IV}
    };
}
